// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/desserts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desserts"
                ],
                "summary": "List desserts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Dessert"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desserts"
                ],
                "summary": "Create dessert",
                "parameters": [
                    {
                        "description": "dessert data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Dessert"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Dessert"
                        }
                    }
                }
            }
        },
        "/desserts/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desserts"
                ],
                "summary": "Get desserts by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dessert name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Dessert"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desserts"
                ],
                "summary": "Update desserts by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dessert name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated dessert data (อัปเดตทุกแถวที่ชื่อนี้)",
                        "name": "dessert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Dessert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Desserts"
                ],
                "summary": "Delete desserts by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dessert name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/drinks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drinks"
                ],
                "summary": "List drinks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Drink"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drinks"
                ],
                "summary": "Create drink",
                "parameters": [
                    {
                        "description": "drink data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Drink"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Drink"
                        }
                    }
                }
            }
        },
        "/drinks/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drinks"
                ],
                "summary": "Get drinks by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drink name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Drink"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drinks"
                ],
                "summary": "Update drinks by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drink name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated drink data (จะอัปเดตทุกแถวที่ชื่อนี้)",
                        "name": "drink",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Drink"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drinks"
                ],
                "summary": "Delete drinks by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drink name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "/foods": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Foods"
                ],
                "summary": "List foods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Food"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Foods"
                ],
                "summary": "Create food",
                "parameters": [
                    {
                        "description": "food data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Food"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Food"
                        }
                    }
                }
            }
        },
        "/foods/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Foods"
                ],
                "summary": "Get foods by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Food name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Food"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Foods"
                ],
                "summary": "Update foods by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Food name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated food data (อัปเดตทุกแถวที่ชื่อนี้)",
                        "name": "food",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Food"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Foods"
                ],
                "summary": "Delete foods by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Food name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Dessert": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "sub_category": {
                    "type": "string"
                }
            }
        },
        "main.Drink": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "drink_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "sub_category": {
                    "type": "string"
                }
            }
        },
        "main.Food": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "sub_category": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TLTB Cafe API",
	Description:      "Simple API for cafe menu",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
